#!/usr/bin/env bash
# This script configures the Nginx server so that
# /redirect_me is redirecting to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Define the Nginx configuration file path
nginx_conf="/etc/nginx/sites-available/default"

# Define the location to be redirected
location_to_redirect="/redirect_me"

# Define the new URL for redirection
new_url="https://www.youtube.com/watch?v=QH2-TGUlwu4"

# Use sed to update the Nginx configuration file
# sudo sed -i "/server {/ a \ \ \ \ location $location_to_redirect {\\n \ \ \ \ \ \ \ \ return 301 $new_url;\\n \ \ \ \ }}" $nginx_conf
# sudo sed -i "/server {/ a \ \ \ \ location $location_to_redirect {\\n \ \ \ \ \ \ \ \ return 301 $new_url;\\n \ \ \ \ }}" $nginx_conf
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Reload Nginx to apply the changes
sudo service nginx reload
