#!/usr/bin/env bash
# Installing and configuring HAproxy on your lb-01 server and to send traffic to web-01 and web-02

# installing haproxy on lb-01
sudo apt-get update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get -y install haproxy

# configuring server lb-01 to send traffic to web-01 and and web-02
sudo sed -i -e '$a\\nlisten balancer\n\tbind :80\n\tbalance roundrobin\n\tserver 52744-web-01 54.159.1.148:80 check\n\tserver 52744-web-02 3.85.33.34:80 check\n' /etc/haproxy/haproxy.cfg

sudo service haproxy restart
