#!/usr/bin/env bash
# A bash script to configure Nginx server to listen on port 80

sudo cp /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default.bak
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
