#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.
# Displaying only username, user id and Home directory path for the user

while read -r FREAD
do
  echo "$FREAD" | cut -d ":" -f1,3,6
done < /etc/passwd
