#!/usr/bin/env bash
# Bash script that displays Best School 10 times using while loop but displys Hi after 9th one

i=1
while [ $i -le 10 ]
do
  echo $"My School"
  if [ $i -eq 9 ]
  then
    echo $"Hi"
  fi
  ((i++))
done
