#!/usr/bin/env bash
# Bash script displays number 1 to 20 and displays bad luck from China, Japan and Italy

i=1
while [ $i -le 20 ]
do
  echo $i
  case $i in 
    4)
      echo $"bad luck from China"
      ;;
  esac
  case $i in 
    9)
      echo $"bad luck from Japan"
      ;;
  esac
  case $i in 
    17)
      echo $"bad luck from Italy"
      ;;
  esac
  ((i++))
done
