#!/usr/bin/env bash
# start apache server and return 'hello holberton'

# echo "ServerName localhost" >> /etc/apache2.conf
echo "Hello Holberton" > /var/www/html/index.html
sudo service apache2 status
sudo service apache2 restart
